/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SitemapDotxmlRouteImport } from './routes/sitemap[.]xml'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ApiTrackRouteImport } from './routes/api/track'
import { Route as ApiQualifyRouteImport } from './routes/api/qualify'
import { Route as ApiLeadRouteImport } from './routes/api/lead'
import { Route as ApiHouseholdPilotRouteImport } from './routes/api/household-pilot'
import { Route as LovableEmailTransactionalPreviewRouteImport } from './routes/lovable/email/transactional/preview'

const SitemapDotxmlRoute = SitemapDotxmlRouteImport.update({
  id: '/sitemap.xml',
  path: '/sitemap.xml',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiTrackRoute = ApiTrackRouteImport.update({
  id: '/api/track',
  path: '/api/track',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiQualifyRoute = ApiQualifyRouteImport.update({
  id: '/api/qualify',
  path: '/api/qualify',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiLeadRoute = ApiLeadRouteImport.update({
  id: '/api/lead',
  path: '/api/lead',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiHouseholdPilotRoute = ApiHouseholdPilotRouteImport.update({
  id: '/api/household-pilot',
  path: '/api/household-pilot',
  getParentRoute: () => rootRouteImport,
} as any)
const LovableEmailTransactionalPreviewRoute =
  LovableEmailTransactionalPreviewRouteImport.update({
    id: '/lovable/email/transactional/preview',
    path: '/lovable/email/transactional/preview',
    getParentRoute: () => rootRouteImport,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/api/household-pilot': typeof ApiHouseholdPilotRoute
  '/api/lead': typeof ApiLeadRoute
  '/api/qualify': typeof ApiQualifyRoute
  '/api/track': typeof ApiTrackRoute
  '/lovable/email/transactional/preview': typeof LovableEmailTransactionalPreviewRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/api/household-pilot': typeof ApiHouseholdPilotRoute
  '/api/lead': typeof ApiLeadRoute
  '/api/qualify': typeof ApiQualifyRoute
  '/api/track': typeof ApiTrackRoute
  '/lovable/email/transactional/preview': typeof LovableEmailTransactionalPreviewRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/api/household-pilot': typeof ApiHouseholdPilotRoute
  '/api/lead': typeof ApiLeadRoute
  '/api/qualify': typeof ApiQualifyRoute
  '/api/track': typeof ApiTrackRoute
  '/lovable/email/transactional/preview': typeof LovableEmailTransactionalPreviewRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/sitemap.xml'
    | '/api/household-pilot'
    | '/api/lead'
    | '/api/qualify'
    | '/api/track'
    | '/lovable/email/transactional/preview'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/sitemap.xml'
    | '/api/household-pilot'
    | '/api/lead'
    | '/api/qualify'
    | '/api/track'
    | '/lovable/email/transactional/preview'
  id:
    | '__root__'
    | '/'
    | '/sitemap.xml'
    | '/api/household-pilot'
    | '/api/lead'
    | '/api/qualify'
    | '/api/track'
    | '/lovable/email/transactional/preview'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  SitemapDotxmlRoute: typeof SitemapDotxmlRoute
  ApiHouseholdPilotRoute: typeof ApiHouseholdPilotRoute
  ApiLeadRoute: typeof ApiLeadRoute
  ApiQualifyRoute: typeof ApiQualifyRoute
  ApiTrackRoute: typeof ApiTrackRoute
  LovableEmailTransactionalPreviewRoute: typeof LovableEmailTransactionalPreviewRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/sitemap.xml': {
      id: '/sitemap.xml'
      path: '/sitemap.xml'
      fullPath: '/sitemap.xml'
      preLoaderRoute: typeof SitemapDotxmlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/track': {
      id: '/api/track'
      path: '/api/track'
      fullPath: '/api/track'
      preLoaderRoute: typeof ApiTrackRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/qualify': {
      id: '/api/qualify'
      path: '/api/qualify'
      fullPath: '/api/qualify'
      preLoaderRoute: typeof ApiQualifyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/lead': {
      id: '/api/lead'
      path: '/api/lead'
      fullPath: '/api/lead'
      preLoaderRoute: typeof ApiLeadRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/household-pilot': {
      id: '/api/household-pilot'
      path: '/api/household-pilot'
      fullPath: '/api/household-pilot'
      preLoaderRoute: typeof ApiHouseholdPilotRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/lovable/email/transactional/preview': {
      id: '/lovable/email/transactional/preview'
      path: '/lovable/email/transactional/preview'
      fullPath: '/lovable/email/transactional/preview'
      preLoaderRoute: typeof LovableEmailTransactionalPreviewRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  SitemapDotxmlRoute: SitemapDotxmlRoute,
  ApiHouseholdPilotRoute: ApiHouseholdPilotRoute,
  ApiLeadRoute: ApiLeadRoute,
  ApiQualifyRoute: ApiQualifyRoute,
  ApiTrackRoute: ApiTrackRoute,
  LovableEmailTransactionalPreviewRoute: LovableEmailTransactionalPreviewRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
